//SYSTEM
export const ENABLE_LOGGING = false;
export const ENABLE_DEBUG_ZONE_AREA = false;
export const DEBUG_COLLISION_ALPHA = 0;
export const ENABLE_ENEMIES_COLLISION_LAYER = false;

//PLAYER
export const PLAYER_SPEED = 110;
export const PLAYER_INVULNERABLE_AFTER_HIT_DURATION = 1000;
export const PLAYER_HURT_PUSH_BACK_SPEED = 50;
export const PLAYER_START_MAX_HEALTH = 10;
export const PLAYER_ATTACK_DAMAGE = 2;

//ITEM
export const PLAYER_HEALTH_INCREASE_AMOUNT = 2;
export const PLAYER_ATTACK_INCREASE_AMOUNT = 3;

//POT
export const POT_DAMAGE = 3;

//SPIDER
export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPDIER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENEMY_SPDIER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPDIER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPDIER_PUSH_BACK_SPEED = 50;
export const ENEMY_SPDIER_MAX_HEALTH = 6;


//WISP
export const ENEMY_WISP_SPEED = 50;
export const ENEMY_WISP_PULSE_ANIMATION_X = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_Y = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_DURATION = 1.2;
export const ENEMY_WISP_MAX_HEALTH = 1;

//DROW
export const ENEMY_DROW_SPEED = 80;
export const ENEMY_DROW_MAX_HEALTH = 24;
export const ENEMY_DROW_DEATH_ANIMATION_DURATION = 3000;
export const ENEMY_BOSS_IDLE_STATE_DURATION = 3000;
export const ENEMY_BOSS_HIDDEN_STATE_DURATION = 1000;
export const ENEMY_BOSS_TELEPORT_INITIAL_STATE_DURATION = 150;
export const ENEMY_BOSS_TELEPORT_STATE_FINISHED_DURATION = 500;
export const ENEMY_BOSS_ATTACK_STATE_FINISHED_DELAY = 200;
export const ENEMY_BOSS_START_INITIAL_DELAY = 1000;
export const ENEMY_DROW_ATTACK_DAMAGE = 2;
export const ENEMY_DROW_ATTACK_SPEED = 160;

//HURT 
export const DROW_HURT_PUSH_BACK_DELAY = 50;
export const HURT_PUSH_BACK_DELAY = 200;

export const THROW_ITEM_SPEED = 300;
export const THROW_ITEM_DELAY_BEFORE_CALLBACK = 300;

export const LIFT_ITEM_ANIMATION_DELAY = 0;
export const LIFT_ITEM_ANIMATION_DURATION = 250;
export const LIFT_ITEM_ANIMATION_ENABLE_DEBUGGING = false;

export const CRYSTAL_SCALE = 0.8;

export const ROOM_TRANSITION_PLAYER_INTO_HALL_DURATION = 750;
export const ROOM_TRANSITION_PLAYER_INTO_HALL_DELAY = 250;
export const ROOM_TRANSITION_PLAYER_INTO_NEXT_ROOM_DURATION = 1000;
export const ROOM_TRANSITION_PLAYER_INTO_NEXT_ROOM_DELAY = 1200;
export const ROOM_TRANSITION_CAMERA_ANIMATION_DURATION = 1000;
export const ROOM_TRANSITION_CAMERA_ANIMATION_DELAY = 500;